const ON = "ON";
const OFF = "OFF";
const CREATE = "CREATE";
const DELETE = "DELETE";
const JOIN_EVENT = "JOIN_EVENT";
const LEAVE_EVENT = "LEAVE_EVENT"
export { ON, OFF, CREATE, DELETE,JOIN_EVENT,LEAVE_EVENT  };
